# This is a basic workflow to help you get started with Actions

name: Periodic update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'csv/**'
    - 'json/**'
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */1 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install jq
      run: |
        sudo apt-get install jq
        jq --version

    # Runs a single command using the runners shell
    - name: Run MIZ update
      run: ./update-mizs.sh

    # Runs a single command using the runners shell
    - name: Run OstaniZdrav update
      run: cd ostanizdrav && ./update-ostanizdrav.sh

    # Runs a set of commands using the runners shell
    - name: Check git diff
      run: |
        ls -la json/mizs*
        ls -la csv/mizs*
        git status
        git diff

    # Git commit + push, see https://github.com/github-actions-x/commit
    - name: Publish MIZ changes to git
      if: github.ref == 'refs/heads/master'
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'MIZ Data update '
        rebase: 'true' # pull and rebase before commit
        files: json/mizs* csv/mizs*
        name: Sledilnik data scrape bot 

    # Git commit + push, see https://github.com/github-actions-x/commit
    - name: Publish OstaniZdrav changes to git
      if: github.ref == 'refs/heads/master'
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'OstaniZdrav Data update '
        rebase: 'true' # pull and rebase before commit
        files: ostanizdrav/
        name: Sledilnik data scrape bot 
